version: "3"

services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG --entryPoints="Name:https Address::443 TLS:/ssl/tgl.com.br.crt,/ssl/tgl.com.br.key" --entryPoints="Name:http Address::80" #Redirect.EntryPoint:https"
    ports:
      - "80:80"
      - "9010:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - /mnt/TRAEFIK/ssl:/ssl
    labels:
      - "traefik.enable=false"
    networks:
      - tgl
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
 tgl:
  driver: overlay
  ipam:
   config:
    - subnet: 10.10.10.0/24
